name: PR Workflow by ${{ github.actor }}

on:
  pull_request:

env:
  GITHUB_ACTIONS: true

jobs:
  github-task-job:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: GITHUB_ACTIONS variable
        run: echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"

      - name: Branch and repository name
        run: |
          echo "Branch: ${{ github.head_ref }}"
          echo "Repository: ${{ github.repository }}"

      - name: Event that triggered the workflow
        run: echo "Event ${{ github.event_name }}"
